Python is a high level interpreted programming language. It supports different programming paradigms (object oriented, procedural, functional, etc.). The main characteristic is its simplicity - complicated ideas can be expressed using small number of expressions. Another useful property is extendability.

Example using characteristic expression for implementation of quicksort() function:

In [1]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    pivot = arr[len(arr) // 2]
    left = [x for x in arr if x < pivot]
    middle = [x for x in arr if x == pivot]
    right = [x for x in arr if x > pivot]
    return quicksort(left) + middle + quicksort(right)

print(quicksort([3,6,31,10,1,8,1]))

[1, 1, 3, 6, 8, 10, 31]


Basic data types: integer, float, boolean, string

In [2]:
# integer, float
x = 5
print(type(x)) # prints "<class 'int'>"
print(x)       # prints 3

<class 'int'>
5


In [ ]:
print(x+10)   
print(x-10)   
print(x*10)   # Multiplication
print(x**3)  # Exponential
x += 1      # x=x+1
print(x)  
x *= 3  # x=3*x
print(x) 

15
-5
50
125
6
18


In [ ]:
y = 5.7
print(type(y)) # prints "<class 'float'>"
print(y, y + 1, y * 2, y ** 2) 

<class 'float'>
5.7 6.7 11.4 32.49


In [ ]:
#Boolean:
t = True
f = False
print(type(t)) # prints "<class 'bool'>"
print(t and f) # logic AND
print(t or f)  # logic OR
print(not t)   # logic NOT
print(t != f)  # logic XOR

<class 'bool'>
False
True
False
True


In [5]:
# String
hello = 'hello'    # or:
world = "world"    
print(hello)       

hello


In [6]:
print(len(hello))  # string length
hw = hello + ' ' + world  # concatenation
print(hw)  # prints "hello world"

5
hello world


In [ ]:
s = "hello"
print(s.capitalize())  # Capitalizes first letter
print(s.upper())       # Converts the whole string into capital letters
print(s.rjust(7))      # right adjustment
print(s.center(7))     # centaring, the rest is filled with spaces
print(s.replace('l', '(ell)'))  # replaces the first appearance of the specified string
                                
print('  world '.strip())  # removes starting and ending spaces

Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


In [ ]:
# Collections: lists, dictionaries, sets, and tuples

In [ ]:
# lists, can contain different data types, can change size
xs = [5, 7, 2]    # create list object
print(xs, xs[2])  
print(xs[-1])     # negative index counts backwards, -1 is the last element
xs[2] = 'abc'     # lists can contain different types
print(xs)         

[5, 7, 2] 2
2
[5, 7, 'abc']


In [ ]:
xs.append('efg')  # appending the element to the end of a list
print(xs)         
x = xs.pop()      # removes the last element, and the function returns its value
print(x, xs)      

[5, 7, 'abc', 'efg']
efg [5, 7, 'abc']


In [ ]:
# Slicing lists
nums = list(range(5))     # range is a built in function which resurns list of integers starting with 0
print(nums)               
print(nums[2:4])          # slice from 2 to 4 (DOES NOT include the last element)
print(nums[2:])           # from 2 to the end
print(nums[:2])           # from beginning until 2 (not including 2) 
print(nums[:])            # whole list
print(nums[:-1])          # from first to last (not including last!)
nums[2:4] = [8, 9]        # change two elements
print(nums)               

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


In [9]:
#for loop
animals = ['bird', 'horse', 'dog']
for z in animals:
    print(z)

bird
horse
dog


In [ ]:
# enumerate - useful function which gives you indices
animals = ['bird', 'horse', 'dog']
for idx, z in enumerate(animals):
    print('#%d: %s' % (idx + 1, z))

#1: cat
#2: horse
#3: dog


In [ ]:
# using for loop in one line
b = [0, 1, 2, 3, 4]
b2 = []
for x in b:
    b2.append(x ** 2)
print(b2) 

[0, 1, 4, 9, 16]


In [ ]:
# instead of the above code we can do it one line:
b = [0, 1, 2, 3, 4]
b2 = [x ** 2 for x in b]
print(b2)

[0, 1, 4, 9, 16]


In [ ]:
# if can also be included
b = [0, 1, 2, 3, 4]
parni_b2 = [x ** 2 for x in b if x % 2 == 0]
print(parni_b2)

[0, 4, 16]


In [ ]:
# Dictionary
# It concists of PAIRS of data
d = {'cat': 'white', 'dog': 'black'}  # create object
print(d['cat'])       # takes the value from the dictionary 

white


In [ ]:
d = dict(one=1, two=2, info='some info')
print(d)

{'one': 1, 'two': 2, 'info': 'some info'}


In [ ]:
print('cat' in d)     # Checks if the dictionary has key 'cat'
d['fish'] = 'gray'     # Adding an element
print(d['fish'])     

False
gray


In [ ]:
# SETS
# Set is a collection of elemts, where the order is not important 
#and the elements cannot repeat
#the elements can be of different types
z = {'cat', 'dog'}
print('cat' in z)   # checkis if cat is in the set
print('fish' in z)  # prints False
z.add('fish')       # we add element
print('fish' in z)  # now prints True
print(len(z))       # number f elements in a set
z.add('cat')        # we add element that already exists 
print(len(z))       # which does not have any effect - the lenght is the same
z.remove('cat')     # removing an element
print(len(z))       # prints "2"

True
False
True
3
3
2


In [ ]:
# enumerate - taks arbitrary order
animals = {'cat', 'dog', 'fish'}
for idx, z in enumerate(animals):
    print('#%d: %s' % (idx + 1, z))

#1: fish
#2: cat
#3: dog


In [11]:
# set cannot have double elements:
set([1,2,3,2])

{1, 2, 3}

In [ ]:
A = {1, 2, 3}
A.remove(3)       # remove an element  
print(A)

{1, 2}


In [ ]:
# add an elements to a set 
A = set()
A.update({0, 10})
print(A)
A.update({1, 10})
print(A)

{0, 10}
{0, 1, 10}


In [ ]:
# for loop with sets:
from math import sqrt
nums = {int(sqrt(x)) for x in range(30)}
print(nums) 

{0, 1, 2, 3, 4, 5}


In [ ]:
A=set(range(0,3)) # integers from od 0 do 2
B=set(range(0,6,2)) # even inetegrs from 0 to 6
C=set(range(0,6))  
'A=',A,'B=',B,'C=',C

('A=', {0, 1, 2}, 'B=', {0, 2, 4}, 'C=', {0, 1, 2, 3, 4, 5})

In [ ]:
1 in A, 1 in B, 3 not in B  # chekcs if an element is in a set

(True, False, True)

In [ ]:
A.issubset(C), A<=C

(True, True)

In [ ]:
C.issuperset(B),C>=B

(True, True)

In [ ]:
A.union(B),A | B

({0, 1, 2, 4}, {0, 1, 2, 4})

In [ ]:
A.intersection(B), A&B

({0, 2}, {0, 2})

In [ ]:
A.difference(B), A-B  # set difference, all the elements in A that are not in B 

({1}, {1})

In [ ]:
#Cartesian product
A=set(['a','b','c'])
B=set([1,2])
C=set()
for x in A:
    for y in B:
        C.add((x,y))
C

{('a', 1), ('a', 2), ('b', 1), ('b', 2), ('c', 1), ('c', 2)}

Tuple is an ordered list which cannot be changed. It can contain keys for Dictionaty type, and they can be elements of a set.

In [ ]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)        # Create tuple
print(type(t))    #  "<class 'tuple'>"
print(d[t])       
print(d[(1, 2)])  

<class 'tuple'>
5
1


In [ ]:
# can contain different types
t=('a', 1, 5, 0.01)
print(t)

('a', 1, 5, 0.01)


Functions

In [ ]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 0, 1]:
    print(sign(x))

negative
zero
positive


In [ ]:
def hello(name, loud=False):
    if loud:
        print('HELLO, %s!' % name.upper())
    else:
        print('Hello, %s' % name)

hello('Bob') # Prints "Hello, Bob"
hello('Fred', loud=True)  # Prints "HELLO, FRED!"

Hello, Bob
HELLO, FRED!


In [ ]:
# Classes
class HELLO(object):

    # Constructor
    def __init__(self, provided_name):
        self.name = provided_name  

    # Instance method
    def greating(self, loud=False):
        if loud:
            print('HELLO, %s!' % self.name.upper())
        else:
            print('Hello, %s' % self.name)

g = HELLO('Fred')  # Construction of object of the class HELLO
g.greating()            # method calling
g.greating(loud=True)   

Hello, Fred
HELLO, FRED!


NUMPY

Numpy is the basic library for science and technology. Its implemented in C, and its purpose is to increase the execution speed when woring with multidimensional arrays. 

Numpy array is index using tuple of nonnegative integers. Rank of an array is number of dimensions, shape of array is tuple of integers with array length at each dimension. 

In [ ]:
import numpy as np

a = np.array([1, 2, 3])   # Constructing array of rank 1 
print(type(a))            # "<class 'numpy.ndarray'>"
print(a.shape)            # "(3,)"
print(a[0], a[1], a[2])   # "1 2 3"
a[0] = 5                  # Change an element
print(a)                  # "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Rank2 array
print(b.shape)                     
print(b[0, 0], b[0, 1], b[1, 0])   
b

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
import numpy as np

a = np.zeros((2,2))   # Array with all zeros
print(a)              
                     
b = np.ones((1,2))    # All ones array
print(b)              

c = np.full((2,2), 7)  # Fills array with a specified constant
print(c)              
                       
d = np.eye(2)         # Identity matrix
print(d)            

e = np.random.random((2,2))  # Random matrix (uniform distribution)
print(e)                  

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.59689017 0.30885989]
 [0.22824565 0.09031241]]


In [ ]:
# arange, the same as range but within Numpy
np.arange(3)

array([0, 1, 2])

In [14]:
np.arange(3.0)

array([0., 1., 2.])

In [ ]:
np.arange(3,7)

array([3, 4, 5, 6])

In [ ]:
np.arange(3,7,2)

array([3, 5])

In [ ]:
np.linspace(2.0, 3.0, num=5)  # array is created given number of point and the interval beginning and end (includes end point!)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [16]:
np.linspace(2.0, 3.0, num=5, endpoint=False) # doesn't inckude end point

array([2. , 2.2, 2.4, 2.6, 2.8])

In [ ]:
np.linspace(2.0, 3.0, num=5, retstep=True)

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [ ]:
#Slicing of the numpy array 
#Slice must be specified in each dimension
import numpy as np

# rang 2 array, shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# slice: first two rows, and columns 1 and 2
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# Slice does not make a new array in memory - if we cahnge the slice, the original array is also changed! 
print(a[0, 1])   
b[0, 0] = 77     
print(a[0, 1])  

2
77


In [ ]:
# indexing using integers
import numpy as np

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

red_r1 = a[1, :]    # second row of a, the output is of rank 1!
red_r2 = a[1:2, :]  # second row of a, the output is of rank 2!
print(red_r1, red_r1.shape)  
print(red_r2, red_r2.shape)  

# The same with columns:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape) 
print(col_r2, col_r2.shape)  

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [ ]:
# indexing using array of integers 
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

print(a[[0, 1, 2], [0, 1, 0]]) 

[1 4 5]


In [ ]:
# Indexing using boolean
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  

print(bool_idx)    

print(a[bool_idx])  # Returns list of elements larger than 2 (rank 1)!

# Can be done in one line:
print(a[a > 2])    

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]


In [ ]:
# Data types in numpy arrays
import numpy as np

x = np.array([1, 2])   # Numpy chooses the type
print(x.dtype)      

x = np.array([1.0, 2.0])
print(x.dtype)             # "float64"

x = np.array([1, 2], dtype=np.float64)   # Forsing particular type
print(x.dtype)                         

int32
float64
float64


In [ ]:
# Elementaray mathematical function on arrays (they are applied element-wise!)
import numpy as np

x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# adding
print(x + y)
print(np.add(x, y))

# subtracting
print(x - y)
print(np.subtract(x, y))

# product (element-wise!) 
print(x * y)
print(np.multiply(x, y))

# division
print(x / y)
print(np.divide(x, y))

# square root
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


In [ ]:
# .dot is used for matrix and vector multiplication 
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Dot product
print(v.dot(w))
print(np.dot(v, w))

# Left product
print(x.dot(v))
print(np.dot(x, v))

# Matrix product
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [ ]:
# some function with numpy arrays 
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # sum of all the elements
print(np.sum(x, axis=0))  # sum of all the columns
print(np.sum(x, axis=1))  # sum of all the rows


10
[4 6]
[3 7]


In [ ]:
x = np.array([[1,2], [3,4]])
print(x)    
print(x.T)  # transpose

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
# Broadcasting

import numpy as np


# Instead of the folowing code for adding a vector v to each row i, using for loop:


# Dodavanje vektora v svakoj vrsti i formiranje niza y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)  

# pomocu eksplicitne petlje
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
# And instead of the following way:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # postavlja 4 kopije vektora v jedan na drugi
print(vv)                

y = x + vv 
print(y)  

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [ ]:
# We can do it more quckly in the follwoing way:
import numpy as np

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Numpy automatically expands v (the smaller elements; it must have at least one dimension of size 1) 
           #so that it has the same dimensions as the bigger one  (the rest of the dimensions must be the same!)
print(y)  
        

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Exercises:
1. Find an element of a numpy array which is the closest to a given scalar. 
2. Create a 10x10 array with random elements, and find minimal and maximal values. 
3. Find indices of the nonzero elements of the array [1,2,0,0,4,0].
4. Create a random vector of size 30 and find the mean value of its elements.
5. Find the product of an arbitrary 5x3 matrix and arbitrary 3x2 matrix. 

In [30]:
#1
import numpy as np

arr = np.array([3, 8, 15, 17])
x = 10

closest = arr[np.argmin(np.abs(arr - x))]
print(closest)


8


In [33]:
#2
import numpy as np

numbers = np.random.randint(0, 100, (10,10))

print(numbers)
print("Maximum:", numbers.max())
print("Minimum:", numbers.min())

[[98 69 97 15 70 28 93 67 23 78]
 [34 69 52 21 34 94 87 33 79 83]
 [25 78 99 34 73 28  4 15 90 43]
 [15 43 33 11 40 21 85 74 70  8]
 [77 43 35 44 57 70 60 90  9 27]
 [10 72 62 60 11 96 83 32 93 72]
 [ 9  0 93 91 85 14 87 30 54 28]
 [67 31 57 38 27 57 78 89 42 39]
 [16 99 59 80 78 54 96 58 62  8]
 [15 22 71 15  2 51 52 49 30 45]]
Maximum: 99
Minimum: 0


In [31]:
#3

import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])

indices = np.nonzero(arr)
print(indices)

(array([0, 1, 4]),)


In [34]:
#4

import numpy as np

# Create a random vector of size 30 (values between 0 and 1)
vec = np.random.rand(30)

# Calculate the mean value
mean_val = np.mean(vec)

print("Vector:", vec)
print("Mean value:", mean_val)


Vector: [0.69452129 0.96808321 0.88458714 0.29615064 0.6925473  0.36186231
 0.33524319 0.2004028  0.35801473 0.37327544 0.23101077 0.61567868
 0.94569057 0.43341383 0.73962937 0.62589551 0.47571192 0.45189444
 0.09221215 0.78473258 0.2958028  0.05799549 0.46954353 0.4986791
 0.7334138  0.45344508 0.2958163  0.83150061 0.1834809  0.89112287]
Mean value: 0.5090452794731413


In [35]:
#5 

import numpy as np

# Create a random 5x3 matrix
A = np.random.rand(5, 3)

# Create a random 3x2 matrix
B = np.random.rand(3, 2)

# Multiply the matrices
C = A @ B  # or np.dot(A, B)

print("Matrix A (5x3):\n", A)
print("Matrix B (3x2):\n", B)
print("Product C (5x2):\n", C)


Matrix A (5x3):
 [[0.03146939 0.54906879 0.22229037]
 [0.82228728 0.9646008  0.03643253]
 [0.15130935 0.93631902 0.40881581]
 [0.22753688 0.93984199 0.6516508 ]
 [0.65276079 0.59946133 0.48884097]]
Matrix B (3x2):
 [[0.89807493 0.35299368]
 [0.8819491  0.47093202]
 [0.7745394  0.26493884]]
Product C (5x2):
 [[0.68468525 0.32857593]
 [1.61742283 0.75417601]
 [1.2783168  0.60266504]
 [1.53796719 0.69556838]
 [1.49354908 0.64223893]]
